AGSistemasVeiculos_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('controle.urls')),
    path('', include('carro.urls')),
    path('motorista/', include('motorista.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [
    path('register_new_car/', views.register_new_car, name='register_new_car'),
    path('delete_car/<int:pk>/', views.delete_car, name='delete_car'),
    path('update_car/<int:pk>/', views.update_car, name='update_car'),
    path('render_form_update_car/<int:pk>/', views.render_form_update_car, name='render_form_update_car'),
    path('render_form_delete_car/<int:pk>/', views.render_form_delete_car, name='render_form_delete_car'),
]

motorista/urls.py
from django.urls import path
from . import views

app_name = 'motorista'

urlpatterns = [
    path('', views.register_and_list_motorista, name='register_and_list_motorista'),
    path('delete/<int:pk>/', views.delete_motorista, name='delete'),
]

motorista/models.py
from django.db import models
from django.utils.timezone import localtime
from django.utils.translation import gettext_lazy as _

class Motorista(models.Model):
    cod_motorista = models.CharField(_("Codigo do motorista (o id ja é o suficiente)"), max_length=50, blank=True, null=True)
    nome = models.CharField(_("Nome do motorista"), max_length=128, db_index=True, blank=False, null=False)
    telefone = models.CharField(_("Telefone do motorista (whatsapp)"), max_length=64, blank=True, null=True)
    cnh = models.CharField(_("CNH do motorista"), max_length=64, unique=True, db_index=True, blank=False, null=False)
    
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    @property
    def created_at_region(self):
        return localtime(self.created_at).strftime('%d/%m/%Y %H:%M')
    
    @property
    def updated_at_region(self):
        return localtime(self.updated_at).strftime('%d/%m/%Y %H:%M')

    def __str__(self):
        return self.nome

    class Meta:
        db_table = 'motoristas'
        managed = True
        verbose_name = 'Mtorista'
        verbose_name_plural = 'Mtoristas'

motorista/forms.py
from django import forms


from .models import Motorista

class MotoristaForm(forms.ModelForm):
    class Meta:
        model = Motorista
        fields = ('cod_motorista', 'nome', 'telefone', 'cnh')
        
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['cod_motorista'].widget.attrs.update({
            'class': 'input input-bordered w-full',
            'placeholder': 'Id do motorista',
        })
        self.fields['nome'].widget.attrs.update({
            'class': 'input input-bordered w-full',
            'placeholder': 'Nome do motorista',
        })
        self.fields['telefone'].widget.attrs.update({
            'class': 'input input-bordered w-full',
            'placeholder': 'Telefone do motorista',
        })
        self.fields['cnh'].widget.attrs.update({
            'class': 'input input-bordered w-full',
            'placeholder': 'CNH do motorista',
            })

motorista/views.py
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render

from motorista.forms import MotoristaForm
from motorista.models import Motorista

def register_and_list_motorista(request: HttpRequest) -> HttpResponse:
    form = MotoristaForm
    if request.method == 'POST':
        form = MotoristaForm(request.POST)
        if form.is_valid():
            form.save()
    motoristas = Motorista.objects.all()
    context = {
        "form": form,
        "motoristas": motoristas
    }
    return render(request, 'motorista/list_and_register_motorista.html', context)

def delete_motorista(request: HttpRequest, pk: int) -> HttpResponse:
    motorista = Motorista.objects.get(pk=pk)
    motorista.delete()
    return redirect('motorista:register_and_list_motorista')

motorista/templates/motorista/list_and_register_motorista.html
{% extends "core/base.html" %}

{% block content %}
<section class="min-h-screen p-5 container flex justify-center items-center flex-col mt-12">
  <div class="w-full max-w-md">
    <h1 class="text-3xl mb-4">Registre um novo Motorista!</h1>
    <form action="{% url "motorista:register_and_list_motorista" %}" method="post" class="space-y-4">
      {% csrf_token %}
      {{ form.as_p }}
      <button type="submit" class="btn btn-success w-full">Novo Motorista</button>
    </form>
  </div>
  <div class="overflow-x-auto mt-5 w-full">
    <table class="table w-full">
      <thead>
        <tr>
          <th>#</th>
          <th>Cod. Motorista</th>
          <th>Nome</th>
          <th>Telefone</th>
          <th>CNH</th>
          <th>Ações</th>
        </tr>
      </thead>
      <tbody>
        {% for motorista in motoristas %}
        <tr class="hover">
          <th>{{ forloop.counter }}</th>
          <td>{{ motorista.cod_motorista }}</td>
          <td>{{ motorista.nome }}</td>
          <td>{{ motorista.telefone }}</td>
          <td>{{ motorista.cnh }}</td>
          <td>
            <div class="btn-group">
              <button class="btn btn-xs btn-warning"><img src="https://www.svgrepo.com/show/532995/pen-square.svg" class="icon" alt="editar"></button>
              <button class="btn btn-xs btn-error" onclick="delete_modal_{{motorista.pk}}.showModal()"><img src="https://www.svgrepo.com/show/434383/garbage.svg" alt="excluir" class="icon"></button>
            </div>
          </td>
        </tr>
        <dialog id="delete_modal_{{motorista.pk}}" class="modal">
          <div class="modal-box">
            <h3 class="font-bold text-lg">Deletar {{motorista}} ?</h3>
            <p class="py-4">Tem certeza que deseja deletar ?</p>
            <div class="modal-action">
              <form method="dialog" name="asd" id="asd">
                <button type="submit" class="btn btn-success">Não</button>
              </form>
              <form action="{% url "motorista:delete" motorista.pk %}" method="post">
                {% csrf_token %}
                <button class="btn btn-error" type="submit">Sim!</button>
              </form>
            </div>
          </div>
        </dialog>
        {% endfor %}
      </tbody>
    </table>
  </div>
</section>
{% endblock content %}