AGSistemasVeiculos_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('controle.urls')),
    path('', include('carro.urls')),
    path('motorista/', include('motorista.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [
    path('register_new_car/', views.register_new_car, name='register_new_car'),
    path('delete_car/<int:pk>/', views.delete_car, name='delete_car'),
    path('update_car/<int:pk>/', views.update_car, name='update_car'),
    path('render_form_update_car/<int:pk>/', views.render_form_update_car, name='render_form_update_car'),
    path('render_form_delete_car/<int:pk>/', views.render_form_delete_car, name='render_form_delete_car'),
]

controle/urls.py
from django.urls import path
from . import views

app_name = 'controle'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:pk>/', views.delete_regisro_controle, name='delete'),
    path('update/<int:pk>/', views.update_regisro_controle, name='update'),
    path('render_form_update/<int:pk>/', views.render_form_update_controle_registro, name='render_form_update'),
    path('render_table_list/', views.render_table_list_controle_registro, name='render_table_list'),
]

controle/models.py
from typing import Iterable
from django.db import models
from django.utils.timezone import localtime

from carro.models import Veiculo
from motorista.models import Motorista

class ControleRegistro(models.Model):
    veiculo = models.ForeignKey(Veiculo, on_delete=models.CASCADE, blank=False, null=False, related_name='registros')
    motorista = models.ForeignKey(Motorista, on_delete=models.CASCADE, blank=False, null=False, related_name='registros')
    destino = models.CharField('Destino', max_length=50, blank=False, null=False)
    saida = models.DateTimeField('Data e hora da Saida', blank=False, null=False)
    retorno = models.DateTimeField('Data e hora do Retorno', blank=True, null=True)
    km_saida = models.IntegerField('Km Saida', default=0)
    km_retorno = models.IntegerField('Km Retorno', default=0)
    km_pecorrido = models.IntegerField('Km Percorrido (campo sera calculado automaticamente apos salvar)', default=0)
    
    created_at = models.DateTimeField('Criado em', auto_now_add=True)
    updated_at = models.DateTimeField('Atualizado em', auto_now=True)
    
    def save(self, *args, **kwargs):
        self.km_pecorrido = self.km_retorno + self.km_saida
        if not self.pk:
            #se for novo registro
            self.veiculo.km_troca_oleo -=  self.km_pecorrido
            self.veiculo.save()
        super(ControleRegistro, self).save(*args, **kwargs)
    
    @property
    def created_at_region(self):
        return localtime(self.created_at).strftime('%d/%m/%Y %H:%M')
    
    @property
    def updated_at_region(self):
        return localtime(self.updated_at).strftime('%d/%m/%Y %H:%M')

    def __str__(self):
        return f"{self.veiculo} | {self.motorista} | {self.km_pecorrido}"

    class Meta:
        db_table = 'controle_registros'
        managed = True
        verbose_name = 'ControleRegistro'
        verbose_name_plural = 'ControleRegistros'

controle/forms.py
from django import forms
from .models import ControleRegistro

class ControleRegistroForm(forms.ModelForm):
    class Meta:
        model = ControleRegistro
        fields = ['veiculo', 'motorista', 'destino', 'saida', 'retorno', 'km_saida', 'km_retorno']
        widgets = {
            'veiculo': forms.Select(attrs={'class': 'input input-bordered w-full'}),
            'motorista': forms.Select(attrs={'class': 'input input-bordered w-full'}),
            'destino': forms.TextInput(attrs={'class': 'input input-bordered w-full'}),
            'saida': forms.DateTimeInput(attrs={'class': 'input input-bordered w-full', 'type': 'date'}),
            'retorno': forms.DateTimeInput(attrs={'class': 'input input-bordered w-full', 'type': 'date'}),
            'km_saida': forms.TextInput(attrs={
                'class': 'input input-bordered w-full', 
                'type': 'number', 
                'step': '1', 
                'min': '0'
            }),
            'km_retorno': forms.TextInput(attrs={
                'class': 'input input-bordered w-full', 
                'type': 'number',
                'step': '1',
                'min': '0'
            }),
        }

controle/views.py
import json
from django.http import HttpRequest, HttpResponse
from django.shortcuts import redirect, render
from django.template import loader

from carro.models import Veiculo
from controle.forms import ControleRegistroForm
from controle.models import ControleRegistro
from motorista.models import Motorista

def home(request: HttpRequest) -> HttpResponse:
    form = ControleRegistroForm
    if request.method == 'POST':
        form = ControleRegistroForm(request.POST)
        if form.is_valid():
            form.save()
    registros = ControleRegistro.objects.all().select_related(
        'veiculo', 
        'motorista'
    ).order_by('-saida')
    veiulos = Veiculo.objects.all()
    motoristas = Motorista.objects.all()
    context = {
        'form': form,
        'registros': registros,
        'veiculos': veiulos,
        'motoristas': motoristas
    }
    return render(request, 'controle/index.html', context)


def delete_regisro_controle(request: HttpRequest, pk: int) -> HttpResponse:
    controle = ControleRegistro.objects.get(pk=pk)
    controle.delete()
    return redirect('controle:home')


def update_regisro_controle(request: HttpRequest, pk: int) -> HttpResponse:
    controle = ControleRegistro.objects.get(pk=pk)
    form = ControleRegistroForm(instance=controle)
    if request.method == 'POST':
        form = ControleRegistroForm(request.POST, instance=controle)
        if form.is_valid():
            form.save()
    context = {
        'form': form
    }
    return redirect('controle:home')

def render_form_update_controle_registro(request: HttpRequest, pk: int) -> HttpResponse:
    controle = ControleRegistro.objects.get(pk=pk)
    form = ControleRegistroForm(instance=controle)
    context = {
        'form': form,
        'registro': controle
    }
    return HttpResponse(loader.render_to_string(
        'controle/layouts/_form_controle.html',
        context,
        request=request))
    
    
def render_table_list_controle_registro(request: HttpRequest) -> HttpResponse:
    if request.method == 'POST':
        data = json.loads(request.body)
        filtrar_data_registro = data.get('filtrar-data-registro')
        
        registros = ControleRegistro.objects.filter(
            saida__icontains=filtrar_data_registro
        ).select_related(
            'veiculo', 
            'motorista'
        ).order_by('-saida')
        context = {
            'registros': registros
        }
        return HttpResponse(loader.render_to_string(
            'controle/layouts/_table_list_controle.html',
            context,
            request=request))
    return HttpResponse('Metodo não aceito')

controle/templates/controle/layouts/_form_controle.html
<form action="{% url "controle:update" registro.pk %}" method="post" class="py-4 space-y-4">
  {% csrf_token %}
  {{form.as_p}}
  <div class="modal-action">
    <button type="submit" class="btn btn-primary">Salvar</button>
    <button type="button" class="btn" onclick="edit_modal.close()">Cancelar</button>
  </div>
</form>

controle/templates/controle/layouts/_table_list_controle.html
<table id="table-list-controle" class="table w-full">
  <thead>
    <tr>
      <th></th>
      <th>Veículo</th>
      <th>Motorista</th>
      <th>Data Saída</th>
      <th>Ações</th>
    </tr>
  </thead>
  <tbody>
    {% for registro in registros %}
    <tr>
      <th>{{ forloop.counter }}</th>
      <td>{{ registro.veiculo}}</td>
      <td>{{ registro.motorista }}</td>
      <td>{{ registro.saida|date:"d/m/Y H:i" }}</td>
      <td>
        <div class="btn-group">
          <button 
            class="btn btn-xs btn-info">
            <img 
              src="https://www.svgrepo.com/show/513029/view-simple-815.svg" 
              onclick="view_modal_{{registro.pk}}.showModal()" 
              alt="Vizualizar" 
              class="icon">
            </button>
          <button 
            class="btn btn-xs btn-warning">
            <img 
              src="https://www.svgrepo.com/show/532995/pen-square.svg" 
              onclick="renderUpdateForm({{ registro.pk }})" 
              class="icon"  
              alt="editar">
            </button>
          <button 
            class="btn btn-xs btn-error">
              <img 
                src="https://www.svgrepo.com/show/434383/garbage.svg" 
                onclick="delete_modal_{{registro.pk}}.showModal()" 
                alt="excluir" 
                class="icon">
            </button>
        </div>
      </td>
    </tr>
    <dialog id="view_modal_{{ registro.pk }}" class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Dados de {{ registro }}</h3>
        <div class="py-4 space-y-2">
          <p><strong>Veículo:</strong> {{ registro.veiculo}}</p>
          <p><strong>Motorista:</strong> {{ registro.motorista.nome }}</p>
          <p><strong>Data e Hora de Saída:</strong> {{ registro.saida|date:"d/m/Y H:i" }}</p>
          <p><strong>Data e Hora de Retorno:</strong> {% if registro.retorno %}{{ registro.retorno|date:"d/m/Y H:i" }}{% else %}Ainda não retornou{% endif %}</p>
          <p><strong>Quilometragem de Saída:</strong> {{ registro.km_saida }}</p>
          <p><strong>Quilometragem de Retorno:</strong> {% if registro.km_retorno %}{{ registro.km_retorno }}{% else %}Ainda não registrado{% endif %}</p>
          <p><strong>Quilometragem Percorrida:</strong> {% if registro.km_pecorrido %}{{ registro.km_pecorrido }}{% else %}Ainda não registrado{% endif %}</p>
          <p><strong>Destino:</strong> {{ registro.destino }}</p>
        </div>
        <div class="modal-action">
          <form method="dialog" name="asd" id="asd">
            <button type="submit" class="btn">Fechar</button>
          </form>
        </div>
      </div>
    </dialog>
    <dialog id="delete_modal_{{registro.pk}}" class="modal">
      <div class="modal-box">
        <h3 class="font-bold text-lg">Deletar {{registro}} ?</h3>
        <p class="py-4">Tem certeza que deseja deletar ?</p>
        <div class="modal-action">
          <form method="dialog" name="asd" id="asd">
            <button type="submit" class="btn btn-success">Não</button>
          </form>
          <form action="{% url "controle:delete" registro.pk %}" method="post">
            {% csrf_token %}
            <button class="btn btn-error" type="submit">Sim!</button>
          </form>
        </div>
      </div>
    </dialog>
    {% endfor %}
  </tbody>
</table>