AGSistemasVeiculos_project/urls.py
from django.conf import settings
from django.conf.urls.static import static

from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('controle.urls')),
    path('', include('carro.urls')),
    path('motorista/', include('motorista.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

carro/urls.py
from django.urls import path
from . import views

app_name = 'carro'

urlpatterns = [
    path('register_new_car/', views.register_new_car, name='register_new_car'),
    path('delete_car/<int:pk>/', views.delete_car, name='delete_car'),
    path('update_car/<int:pk>/', views.update_car, name='update_car'),
    path('render_form_update_car/<int:pk>/', views.render_form_update_car, name='render_form_update_car'),
    path('render_form_delete_car/<int:pk>/', views.render_form_delete_car, name='render_form_delete_car'),
]

controle/urls.py
from django.urls import path
from . import views

app_name = 'controle'

urlpatterns = [
    path('', views.home, name='home'),
    path('delete/<int:pk>/', views.delete_regisro_controle, name='delete'),
    path('update/<int:pk>/', views.update_regisro_controle, name='update'),
    path('render_form_update/<int:pk>/', views.render_form_update_controle_registro, name='render_form_update'),
    path('render_table_list/', views.render_table_list_controle_registro, name='render_table_list'),
]

motorista/urls.py
from django.urls import path
from . import views

app_name = 'motorista'

urlpatterns = [
    path('', views.register_and_list_motorista, name='register_and_list_motorista'),
    path('delete/<int:pk>/', views.delete_motorista, name='delete'),
]

core/templates/core/base.html
{% load static %}
<!DOCTYPE html>
<html lang="pt-br" data-theme="dracula">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="{% static "css/daisyUI_4.10.css" %}" data-theme="light">
    <title>{% block title %}{% endblock title %}</title>
    {% block head %}{% endblock head %}
    <style>
      .icon {
        width: 15px;
      }
    </style>
</head>
<body>
    
    <main id="root" class="flex">
        <div class="drawer lg:drawer-open">
            <input id="my-drawer-2" type="checkbox" class="drawer-toggle" />
            <div class="drawer-content flex flex-col items-center justify-center">
              {% block content %}{% endblock content %}
              <label for="my-drawer-2" class="btn btn-secondary drawer-button lg:hidden fixed top-4 left-4"><strong>>></strong></label>
            
            </div> 
            <div class="drawer-side">
              <label for="my-drawer-2" aria-label="close sidebar" class="drawer-overlay"></label> 
              <ul class="menu p-4 w-80 min-h-full bg-base-200 text-base-content gap-3 center">
                <!-- Sidebar content here -->
                <li><a class="btn btn-primary" href="{% url "controle:home" %}">Pagina Inicial </a></li>
                <li><a class="btn btn-secondary btn-sm" href="{% url "carro:register_new_car" %}">Veiculos</a></li>
                <li><a class="btn btn-secondary btn-sm" href="{% url "motorista:register_and_list_motorista" %}">Motoristas</a></li>
                <label for="my-drawer-2" class="btn btn-error drawer-button md:hidden lg:hidden fixed bottom-4 left-4 strong"><strong><<</strong></label>
              </ul>
            </div>
          </div>
        {% comment %} {% include "core/layouts/sidebar.html" %} {% endcomment %}
    </main>
    {% include "core/layouts/footer.html" %}
    {% block scripts %}{% endblock scripts %}
    <script src="{% static "js/tailwind_3.4.js" %}"></script>
</body>
</html>